### ISSUE TITLE
could you add instructions to the readme please

### ISSUE THREAD

**Issue by mrantonwinter** [adrianliaw/meteor-youtube-iframe-api#1]
Hi,

i am having difficulty working out how to use your package to access the youtube api.

the error i am getting is 
"Uncaught ReferenceError: YTConfig is not defined "  in www-widgetapi.js line 36.

Thanks in advance

**Comment by adrianliaw** [comment]
Thanks, 
I fixed the bugs, and also added a README, enjoy ^^
