### ISSUE TITLE
Browser refuses to load script

### ISSUE THREAD

**Issue by dajocarter** [adrianliaw/meteor-youtube-iframe-api#4]
After adding the package, the browser showed the following error: 
`Refused to load the script 'https://s.ytimg.com/yts/jsbin/www-widgetapi-vfldTtH0_/www-widgetapi.js?_=1444777748622' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".`
Stemming from the last line in this code:
`$(document).ready(function () {
                var a = document.createElement('script');
                a.id = 'www-widgetapi-script';
                a.src = 'https:' + '//s.ytimg.com/yts/jsbin/www-widgetapi-vfldTtH0_/www-widgetapi.js';
                $("head").append(a);
            });`

**Comment by dajocarter** [comment]
Adding the `browser-policy` package and the following code fixed the issue.

```
BrowserPolicy.framing.disallow();
BrowserPolicy.content.disallowInlineScripts();
BrowserPolicy.content.disallowEval();
BrowserPolicy.content.allowInlineStyles();
BrowserPolicy.content.allowFontDataUrl();
BrowserPolicy.content.allowOriginForAll("https://*.youtube.com");
BrowserPolicy.content.allowOriginForAll("https://*.ytimg.com");
```

**Comment by adrianliaw** [comment]
Thanks for reporting, @dajocarter. Well it works pretty well in my browser, I didn't see any error message that you described. Which browser are you using?

**Comment by dajocarter** [comment]
I was using Chrome.
